// popular cities of bihar, jharkhand and big indian cities
const exploreLinks = [
    {
        label: "Explore Jobs in cities",
        prefix: "Jobs in",
        data: [
            "Patna",
            "Ranchi",
            "Jamshedpur",
            "Dhanbad",
            "Bokaro",
            "Muzaffarpur",
            "Gaya",
            "Bhagalpur",
            "Purnia",
            "Darbhanga",
            "Ara",
            "Bihar Sharif",
            "Munger",
            "Chapra",
            "Danapur",
            "Bettiah",
            "Saharsa",
            "Sasaram",
            "Hajipur",
            "Dehri",
            "Siwan",
            "Motihari",
            "Nawada",
            "Bagaha",
            "Buxar",
            "Kishanganj",
            "Sitamarhi",
            "Jamalpur",
            "Jehanabad",
            "Aurangabad",
            "Lakhisarai",
            "Nokha",
            "Supaul",
            "Bhabua",
            "Barh",
            "Thakurganj",
            "Sherghati",
            "Sheikhpura",
            "Baruni",
            "Baruni",
        ],
    },
    {
        label: "Explore Jobs by Profession",
        prefix: "Job for",
        data: [
            "Software Developer",
            "Data Analyst",
            "Business Analyst",
            "Web Developer",
            "Digital Marketing",
            "Content Writing",
            "Graphic Designer",
            "UI/UX Designer",
            "SEO Expert",
            "Social Media Manager",
            "HR Manager",
            "Sales Manager",
            "Marketing Manager",
            "Finance Manager",
            "Operations Manager",
            "Customer Support",
            "Customer Success",
            "Customer Relationship Manager",
            "Customer Service",
            "Customer Care",
            "Customer Retention",
            "Customer Acquisition",
            "Customer Engagement",
            "Customer Experience",
            "Customer Feedback",
            "Customer Satisfaction",
            "Customer Loyalty",
            "Customer Journey",
            "Customer Advocacy",
        ],
    },
    {
        label: "Popular Jobs",
        prefix: "",
        data: [
            "Accounts / Finance Jobs",
            "Sales (Field Work)",
            "Human Resource",
            "Backoffice Jobs",
            "Business Development",
            "Telecaller / BPO",
            "Work from Home Jobs",
            "Part Time Jobs",
            "Full Time Jobs",
            "Night Shift Jobs",
            "Freshers Jobs",
            "Internship Jobs",
            "Online Jobs",
            "Freelance Jobs",
            "Remote Jobs",
        ],
    },
];

export {exploreLinks};

export const footerLinks = [
    {
        label: "Companies",
        path: "/jobs",
        newTab: false,
    },
    {
        label: "Recriutment",
        path: "/",
        newTab: false,
    },
    {
        label: "FAQs",
        path: "/support",
        newTab: false,
    },
    {
        label: "Help Center",
        path: "/support",
        newTab: false,
    },
];
