// popular cities of bihar, jharkhand and big indian cities
export const exploreLinks = {
    citynames: [
        "Patna",
        "Ranchi",
        "Jamshedpur",
        "Dhanbad",
        "Bokaro",
        "Muzaffarpur",
        "Gaya",
        "Bhagalpur",
        "Purnia",
        "Darbhanga",
        "Ara",
        "Bihar Sharif",
        "Munger",
        "Chapra",
        "Danapur",
        "Bettiah",
        "Saharsa",
        "Sasaram",
        "Hajipur",
        "Dehri",
        "Siwan",
        "Motihari",
        "Nawada",
        "Bagaha",
        "Buxar",
        "Kishanganj",
        "Sitamarhi",
        "Jamalpur",
        "Jehanabad",
        "Aurangabad",
        "Lakhisarai",
        "Nokha",
        "Supaul",
        "Bhabua",
        "Barh",
        "Thakurganj",
        "Sherghati",
        "Sheikhpura",
        "Baruni",
        "Baruni",
    ],
    professions: [
        "Software Developer",
        "Data Analyst",
        "Business Analyst",
        "Web Developer",
        "Digital Marketing",
        "Content Writing",
        "Graphic Designer",
        "UI/UX Designer",
        "SEO Expert",
        "Social Media Manager",
        "HR Manager",
        "Sales Manager",
        "Marketing Manager",
        "Finance Manager",
        "Operations Manager",
        "Customer Support",
        "Customer Success",
        "Customer Relationship Manager",
        "Customer Service",
        "Customer Care",
        "Customer Retention",
        "Customer Acquisition",
        "Customer Engagement",
        "Customer Experience",
        "Customer Feedback",
        "Customer Satisfaction",
        "Customer Loyalty",
        "Customer Journey",
        "Customer Advocacy",
    ],
    popularJobs: [
        "Delivery Person Jobs",
        "Accounts / Finance Jobs",
        "Sales (Field Work)",
        "Human Resource",
        "Backoffice Jobs",
        "Business Development",
        "Telecaller / BPO",
        "Work from Home Jobs",
        "Part Time Jobs",
        "Full Time Jobs",
        "Night Shift Jobs",
        "Freshers Jobs",
        "Internship Jobs",
        "Online Jobs",
        "Freelance Jobs",
        "Remote Jobs",
    ]
};
